services:
  
  app:
    build: ./backend
    container_name: emp_sync_app
    ports:
      - "8000:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # depends_on:
    #   - "standalone"

# for this to work use his command docker compose up --watch 
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml/

  postgres:
    image: postgres:14.5
    container_name: emp_sync_postgres
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data:


networks:
  default:
    name: employee-sync