services:
  
  backend:
    build: ./backend
    container_name: emp-sync-BE
    ports:
      - "8000:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    depends_on:
      - postgres

# for this to work use his command docker compose up --watch 
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml/

  postgres:
    image: postgres:14.5
    container_name: emp_sync_postgres
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: emp-sync-FE
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for file change detection inside Docker
    volumes:
      - ./frontend:/app # Mounts the source directory
      - /app/node_modules # Ensures node_modules are container-specific
    depends_on:
      - backend
    command: ["npm", "run", "dev"] # Use dev server in development

volumes:
  postgres_data:

networks:
  default:
    name: employee-sync