services:
  
  app:
    build: ./backend
    container_name: rag_api_container
    ports:
      - "8000:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # depends_on:
    #   - "standalone"

# for this to work use his command docker compose up --watch 
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml/

networks:
  default:
    name: employee-sync